name             'lightnet'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures lightnet'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

depends 'postgresql'
depends 'database'
depends 'rabbitmq'
depends 'python'
depends 'java'
depends 'sudo'
depends 'hostsfile'